#!/bin/sh
# 
# ./build-busybox config
# or ./build-busybox


cc=/home/workspace/program-files/gcc-linaro-7.3.1_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-
export CROSS_COMPILE=${cc}
export CONFIG_SYSROOT=/home/workspace/program-files/gcc-linaro-7.3.1_arm-linux-gnueabihf/arm-linux-gnueabihf/sysroot

if [ "$1" = "config" ]; then
make menuconfig
echo y | cp -f ./.config ./configs/busybox_armv7_defconfig
else

make distclean
make busybox_armv7_defconfig
make && make install
fi

